// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// AddNewProductHandlerFunc turns a function with the right signature into a add new product handler
type AddNewProductHandlerFunc func(AddNewProductParams) middleware.Responder

// Handle executing the request and returning a response
func (fn AddNewProductHandlerFunc) Handle(params AddNewProductParams) middleware.Responder {
	return fn(params)
}

// AddNewProductHandler interface for that can handle valid add new product params
type AddNewProductHandler interface {
	Handle(AddNewProductParams) middleware.Responder
}

// NewAddNewProduct creates a new http.Handler for the add new product operation
func NewAddNewProduct(ctx *middleware.Context, handler AddNewProductHandler) *AddNewProduct {
	return &AddNewProduct{Context: ctx, Handler: handler}
}

/*
AddNewProduct swagger:route POST /users/{userId}/carts/{cartId} addNewProduct

Add a new product to cart
*/
type AddNewProduct struct {
	Context *middleware.Context
	Handler AddNewProductHandler
}

func (o *AddNewProduct) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewAddNewProductParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
