// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"

	"api.trafilea.com/models"
)

// NewAddNewProductParams creates a new AddNewProductParams object
// no default values defined in spec.
func NewAddNewProductParams() AddNewProductParams {

	return AddNewProductParams{}
}

// AddNewProductParams contains all the bound params for the add new product operation
// typically these are obtained from a http.Request
//
// swagger:parameters AddNewProduct
type AddNewProductParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: path
	*/
	CartID string
	/*
	  Required: true
	  In: body
	*/
	ProductInput *models.ProductInput
	/*
	  Required: true
	  In: path
	*/
	UserID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddNewProductParams() beforehand.
func (o *AddNewProductParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCartID, rhkCartID, _ := route.Params.GetOK("cartId")
	if err := o.bindCartID(rCartID, rhkCartID, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.ProductInput
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("productInput", "body", ""))
			} else {
				res = append(res, errors.NewParseError("productInput", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.ProductInput = &body
			}
		}
	} else {
		res = append(res, errors.Required("productInput", "body", ""))
	}
	rUserID, rhkUserID, _ := route.Params.GetOK("userId")
	if err := o.bindUserID(rUserID, rhkUserID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindCartID binds and validates parameter CartID from path.
func (o *AddNewProductParams) bindCartID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CartID = raw

	return nil
}

// bindUserID binds and validates parameter UserID from path.
func (o *AddNewProductParams) bindUserID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.UserID = raw

	return nil
}
