// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateCartHandlerFunc turns a function with the right signature into a create cart handler
type CreateCartHandlerFunc func(CreateCartParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateCartHandlerFunc) Handle(params CreateCartParams) middleware.Responder {
	return fn(params)
}

// CreateCartHandler interface for that can handle valid create cart params
type CreateCartHandler interface {
	Handle(CreateCartParams) middleware.Responder
}

// NewCreateCart creates a new http.Handler for the create cart operation
func NewCreateCart(ctx *middleware.Context, handler CreateCartHandler) *CreateCart {
	return &CreateCart{Context: ctx, Handler: handler}
}

/*
CreateCart swagger:route POST /users/{userId}/carts/ createCart

Create a new cart if it does not exist
*/
type CreateCart struct {
	Context *middleware.Context
	Handler CreateCartHandler
}

func (o *CreateCart) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateCartParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
