// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Trafilea API
//
//	E-commerce platform
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//	Contact: Eddie Riascos<eriascos@trafilea.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
